---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable_freqaitorch
    # # Enable GPU Image and GPU Resources
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqAI
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      download-data 
        --c /freqtrade/user_data/xgboost_config.json
        --timeframes 3m 5m 15m 1h 4h 
        --timerange 20200101-20240101
        

#      download-data
#        --exchange binance 
#        --pairs BTC/USDT
#        --timeframes 1d
#        --timerange 20180101-20231001
      